// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmwyysbjhehkjzaovhcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtd3l5c2JqaGVoa2p6YW92aGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzEzMTAsImV4cCI6MjA3MzU0NzMxMH0.j03TtXbVRszrBXYJe2S7sW-ozxjHr8Rb0rwPzOCx4xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});